image: git.mugg.io:5050/nick/docker-public/cmake-all

stages:
  - test
  - release

test-job:
  stage: test
  script:
    - /opt/cmake-3.12/bin/cmake -S "$CI_PROJECT_DIR" -B /tmp/build
    - /opt/cmake-3.12/bin/ctest --test-dir /tmp/build
