image: git.mugg.io:5050/nick/docker-public/cmake-all

stages:
  - test
  - release

test-job:
  stage: test
  script:
    - mkdir /tmp/build
    - cd /tmp/build
    - /opt/cmake-3.12/bin/cmake $CI_PROJECT_DIR
    - /opt/cmake-3.12/bin/ctest
